begin;

create extension if not exists pgmq;
create extension if not exists pg_cron;

select pgmq.create('ai_jobs');
select pgmq.create('report_jobs');

create table if not exists public.job_runs (
  id bigint generated by default as identity primary key,
  queue_name text not null check (queue_name in ('ai_jobs', 'report_jobs')),
  message_id bigint not null,
  job_type text not null,
  status text not null check (status in ('running', 'completed', 'failed')),
  payload jsonb not null default '{}'::jsonb,
  result jsonb,
  error text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  unique (queue_name, message_id)
);

alter table public.job_runs enable row level security;
revoke all on public.job_runs from anon;
grant select on public.job_runs to authenticated;

drop policy if exists "admin read job runs" on public.job_runs;
create policy "admin read job runs"
on public.job_runs for select to authenticated
using ((select auth.jwt()->'app_metadata'->>'role') = 'admin');

create or replace function public.enqueue_ai_job(
  project_key text,
  job_type text,
  payload jsonb default '{}'::jsonb,
  delay_seconds integer default 0
)
returns bigint
language sql
security definer
set search_path = public, pgmq
as $$
  select pgmq.send(
    'ai_jobs',
    jsonb_build_object(
      'project_key', project_key,
      'job_type', job_type,
      'payload', coalesce(payload, '{}'::jsonb),
      'queued_at', now()
    ),
    greatest(delay_seconds, 0)
  );
$$;

create or replace function public.enqueue_report_job(
  discord_user_id bigint,
  report_year integer,
  report_month integer,
  delay_seconds integer default 0
)
returns bigint
language sql
security definer
set search_path = public, pgmq
as $$
  select pgmq.send(
    'report_jobs',
    jsonb_build_object(
      'user_id', discord_user_id,
      'year', report_year,
      'month', report_month,
      'queued_at', now()
    ),
    greatest(delay_seconds, 0)
  );
$$;

create or replace function public.claim_job(
  target_queue text,
  visibility_seconds integer default 300
)
returns table (
  msg_id bigint,
  read_ct integer,
  enqueued_at timestamptz,
  vt timestamptz,
  message jsonb
)
language plpgsql
security definer
set search_path = public, pgmq
as $$
begin
  if target_queue not in ('ai_jobs', 'report_jobs') then
    raise exception 'Unknown queue: %', target_queue;
  end if;
  return query
    select *
    from pgmq.read(target_queue, greatest(visibility_seconds, 30), 1);
end;
$$;

create or replace function public.archive_job(
  target_queue text,
  target_message_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public, pgmq
as $$
begin
  if target_queue not in ('ai_jobs', 'report_jobs') then
    raise exception 'Unknown queue: %', target_queue;
  end if;
  return pgmq.archive(target_queue, target_message_id);
end;
$$;

create or replace function public.enqueue_previous_month_reports()
returns integer
language plpgsql
security definer
set search_path = public, pgmq
as $$
declare
  report_period date;
  employee record;
  queued integer := 0;
begin
  report_period := (
    date_trunc('month', now() at time zone 'Asia/Bangkok') - interval '1 month'
  )::date;
  for employee in select user_id from public.attendance_employees
  loop
    perform public.enqueue_report_job(
      employee.user_id,
      extract(year from report_period)::integer,
      extract(month from report_period)::integer,
      0
    );
    queued := queued + 1;
  end loop;
  return queued;
end;
$$;

revoke all on function public.enqueue_ai_job(text, text, jsonb, integer) from public;
revoke all on function public.enqueue_report_job(bigint, integer, integer, integer) from public;
revoke all on function public.claim_job(text, integer) from public;
revoke all on function public.archive_job(text, bigint) from public;
revoke all on function public.enqueue_previous_month_reports() from public;

grant execute on function public.enqueue_ai_job(text, text, jsonb, integer) to service_role;
grant execute on function public.enqueue_report_job(bigint, integer, integer, integer) to service_role;
grant execute on function public.claim_job(text, integer) to service_role;
grant execute on function public.archive_job(text, bigint) to service_role;
grant execute on function public.enqueue_previous_month_reports() to service_role;

do $$
begin
  if exists (select 1 from cron.job where jobname = 'monthly-worktime-reports') then
    perform cron.unschedule('monthly-worktime-reports');
  end if;
  perform cron.schedule(
    'monthly-worktime-reports',
    '10 17 1 * *',
    'select public.enqueue_previous_month_reports()'
  );
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'job_runs'
  ) then
    alter publication supabase_realtime add table public.job_runs;
  end if;
end
$$;

commit;
