begin;

create table if not exists public.attendance_employees (
  user_id bigint primary key,
  user_name text not null,
  full_name text,
  daily_rate numeric(12, 2) not null default 400 check (daily_rate >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.attendance_entries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.attendance_employees(user_id),
  user_name text not null,
  work_date date not null,
  clock_in timestamptz,
  clock_out timestamptz,
  status text not null default 'working',
  reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, work_date),
  check (clock_out is null or clock_in is null or clock_out >= clock_in)
);

create index if not exists idx_attendance_entries_user_date
  on public.attendance_entries (user_id, work_date);

create table if not exists public.video_projects (
  id bigint generated by default as identity primary key,
  project_key text not null unique,
  title text not null,
  brief text not null,
  stage text not null default 'idea'
    check (stage in ('idea', 'image_gen', 'storyboard', 'render', 'pending_review', 'review', 'edits', 'approved')),
  owner_id bigint not null,
  owner_name text not null,
  thread_id bigint unique,
  notion_url text,
  drive_url text,
  final_asset_url text,
  approved_by_id bigint,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.video_assets (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.video_projects(id) on delete cascade,
  asset_type text not null
    check (asset_type in ('prompt', 'reference', 'image', 'storyboard', 'video', 'final', 'drive', 'other')),
  url text not null,
  prompt text,
  note text,
  added_by_id bigint not null,
  added_by_name text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_video_assets_project
  on public.video_assets (project_id, created_at);

create table if not exists public.video_costs (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.video_projects(id) on delete cascade,
  amount numeric(14, 4) not null check (amount >= 0),
  unit text not null,
  tool text,
  note text,
  added_by_id bigint not null,
  added_by_name text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_video_costs_project
  on public.video_costs (project_id, created_at);

create table if not exists public.video_events (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.video_projects(id) on delete cascade,
  event_type text not null,
  message text not null,
  actor_id bigint not null,
  actor_name text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_video_events_project
  on public.video_events (project_id, created_at);

alter table public.attendance_employees enable row level security;
alter table public.attendance_entries enable row level security;
alter table public.video_projects enable row level security;
alter table public.video_assets enable row level security;
alter table public.video_costs enable row level security;
alter table public.video_events enable row level security;

revoke all on public.attendance_employees from anon;
revoke all on public.attendance_entries from anon;
revoke all on public.video_projects from anon;
revoke all on public.video_assets from anon;
revoke all on public.video_costs from anon;
revoke all on public.video_events from anon;

grant select, insert, update, delete on public.attendance_employees to authenticated;
grant select, insert, update, delete on public.attendance_entries to authenticated;
grant select, insert, update, delete on public.video_projects to authenticated;
grant select, insert, update, delete on public.video_assets to authenticated;
grant select, insert, update, delete on public.video_costs to authenticated;
grant select, insert, update, delete on public.video_events to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'attendance_employees',
    'attendance_entries',
    'video_projects',
    'video_assets',
    'video_costs',
    'video_events'
  ]
  loop
    execute format('drop policy if exists "admin full access" on public.%I', target_table);
    execute format(
      'create policy "admin full access" on public.%I for all to authenticated using ((select auth.jwt()->''app_metadata''->>''role'') = ''admin'') with check ((select auth.jwt()->''app_metadata''->>''role'') = ''admin'')',
      target_table
    );
  end loop;
end
$$;

insert into storage.buckets (id, name, public, file_size_limit)
values
  ('attendance-reports', 'attendance-reports', false, 10485760),
  ('video-assets', 'video-assets', false, 536870912)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit;

drop policy if exists "admin read workflow storage" on storage.objects;
create policy "admin read workflow storage"
on storage.objects for select to authenticated
using (
  bucket_id in ('attendance-reports', 'video-assets')
  and (select auth.jwt()->'app_metadata'->>'role') = 'admin'
);

drop policy if exists "admin insert workflow storage" on storage.objects;
create policy "admin insert workflow storage"
on storage.objects for insert to authenticated
with check (
  bucket_id in ('attendance-reports', 'video-assets')
  and (select auth.jwt()->'app_metadata'->>'role') = 'admin'
);

drop policy if exists "admin update workflow storage" on storage.objects;
create policy "admin update workflow storage"
on storage.objects for update to authenticated
using (
  bucket_id in ('attendance-reports', 'video-assets')
  and (select auth.jwt()->'app_metadata'->>'role') = 'admin'
)
with check (
  bucket_id in ('attendance-reports', 'video-assets')
  and (select auth.jwt()->'app_metadata'->>'role') = 'admin'
);

drop policy if exists "admin delete workflow storage" on storage.objects;
create policy "admin delete workflow storage"
on storage.objects for delete to authenticated
using (
  bucket_id in ('attendance-reports', 'video-assets')
  and (select auth.jwt()->'app_metadata'->>'role') = 'admin'
);

do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'attendance_employees',
    'attendance_entries',
    'video_projects',
    'video_assets',
    'video_costs',
    'video_events'
  ]
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = target_table
    ) then
      execute format(
        'alter publication supabase_realtime add table public.%I',
        target_table
      );
    end if;
  end loop;
end
$$;

create or replace function public.sync_workflow_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_table text;
  sequence_name text;
  maximum_id bigint;
begin
  foreach target_table in array array[
    'attendance_entries',
    'video_projects',
    'video_assets',
    'video_costs',
    'video_events'
  ]
  loop
    sequence_name := pg_get_serial_sequence('public.' || target_table, 'id');
    execute format('select coalesce(max(id), 0) from public.%I', target_table)
      into maximum_id;
    if maximum_id = 0 then
      perform setval(sequence_name, 1, false);
    else
      perform setval(sequence_name, maximum_id, true);
    end if;
  end loop;
end
$$;

revoke all on function public.sync_workflow_sequences() from public;
grant execute on function public.sync_workflow_sequences() to service_role;

commit;
